version: "3"

services:
  rtmp-streamer:
    build:
      context: rtmp-encoder/
      dockerfile: Dockerfile
    environment:
      FFMPEG_THREADS: "1"    
      url: "rtmp-server/live/b"
## note do not change the internal device names
    devices: 
      - /dev/video0:/dev/video0
      - /dev/snd/:/dev/snd/
  rtmp-server:
    build:
      context: rtmp-server/
      dockerfile: Dockerfile.ubuntu
    stdin_open: true
    tty: true
    ports:
      - "1935:1935"
