version: "3"

services:
  rtmp-streamer:
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    environment:
      FFMPEG_THREADS: "2"      
      url: "rtmp-server/live/b"
    devices: 
      - /dev/video2
    tty: true
