version: "3"

services:
  rtmp-streamer:
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    environment:
      FFMPEG_THREADS: "2"      
      url: "192.168.0.18:1935/live/a"
    devices: 
      - /dev/video0:/dev/video0
      - /dev/snd/:/dev/snd/
    tty: true
